### PR TITLE
Remove unnecessary bold text from urlbar and bookmarks

### PR DESCRIPTION
**Pull request by zWolfrost**
Hi, of course this is nothing but a stylistic change so i understand if it's not accepted, but i felt like the bold text from the urlbar and bookmarks is really unnecessary and stands out too much. If you happen to agree with me, i would really like if these changes were implemented. Thank you for your time

### CODE REVIEW

**Comment by zWolfrost** [comment]
Also, opera gx does not have bold text in these two UI elements, so this change would also really help with increasing the likeness between this theme and opera gx

**Comment by Godiesc** [comment]
hi,
I made that a little bold cause Opera GX has wider letters, maybe is a different font than Firefox but without it the font in Firefox I feel it thinner letters than Opera.

**Comment by zWolfrost** [comment]
Hi, thank you for your response. I understand what you mean, but is it possible that this problem is instead caused by the opacity, which is set to 0.9 in the line below the one that i've edited? Either way, i still think that the bold is way too exaggerated. Please, don't feel forced to merge this pull request; It's a subjective matter, really, so if you don't think so close it. Thank you again

**Comment by Godiesc** [comment]
for now I don't have problem to delete that css rules, maybe in a future I find the right font to replace it. thanks for your help.

**Pull request merged**
